limit_req_zone $binary_remote_addr zone=debianwatch_login:1m rate=10r/m;

server {
    listen 80;
    server_name debian-watch.syamxm.com;
    include /etc/nginx/conf.d/snippets/errors.conf;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $debian_watch http://debian-watch:8111;

    location = /healthz {
        return 404;
    }

    location = /signin {
        limit_req zone=debianwatch_login burst=5 nodelay;
        limit_conn metrics_conn 10;
        proxy_pass $debian_watch;
        include /etc/nginx/conf.d/snippets/proxy_params.conf;
    }

    location /static/ {
        proxy_pass $debian_watch;
        include /etc/nginx/conf.d/snippets/proxy_params.conf;
        proxy_cache_valid 200 10m;
    }

    location / {
        limit_conn metrics_conn 20;
        proxy_pass $debian_watch;
        include /etc/nginx/conf.d/snippets/proxy_params.conf;

        proxy_read_timeout 30s;
    }
}
